import {Data,IProductInput} from '@/types'
import { toSlug } from './utils'

const products: IProductInput[] = [
  // T-Shirts (6 Products)
  {
    name: "Mike Mens Slim-fit Long-Sleeve T-Shirt",
    slug: toSlug("Mike-Mens-Slim-fit-Long-Sleeve-T-Shirt"),
    category: 'T-Shirts',
    brand: 'Mike',
    images: ['/images/p51-1.jpeg', '/images/p51-2.jpeg'],
    price: 21.0,
    listPrice: 0,
    avgRating: 4.71,
    numReviews: 7,
    ratingDistribution: [
      { rating: 1, count: 0 }, { rating: 2, count: 0 },
      { rating: 3, count: 0 }, { rating: 4, count: 2 },
      { rating: 5, count: 5 }
    ],
    numSales: 9,
    countInStock: 11,
    description: 'Made with chemicals safer for human health and environment',
    sizes: ['S','M','L','XL','XXL'],
    colors: ['Green','Red','Black'],
    tags: ['new-arrival'],
    isPublished: true,
    reviews: []
  },
  {
    name: "Jerzees Men's Long-Sleeve T-Shirt",
    slug: toSlug("Jerzees-Mens-Long-Sleeve-T-Shirt"),
    category: 'T-Shirts',
    brand: 'Jerzees',
    images: ['/images/p52-1.avi', '/images/p52-2.avi','/images/p52-3.jpg', '/images/p52-4.jpg','/images/p52-5.jpg'],
    price: 15.06,
    listPrice: 16.03,
    avgRating: 4.0,
    numReviews: 12,
    ratingDistribution: [
      { rating: 1, count: 1 }, { rating: 2, count: 0 },
      { rating: 3, count: 2 }, { rating: 4, count: 4 },
      { rating: 5, count: 5 }
    ],
    numSales: 55,
    countInStock: 13,
    description: 'Double-needle coverstitched front neck with seamless body',
    sizes: ['S','M','L','XL','XXL'],
    colors: ['Yellow','Red','Black'],
    tags: ['best-seller'],
    isPublished: true,
    reviews: []
  },
  {
    name: "Decruz Mens Plain Long Sleeve T-Shirt",
    slug: toSlug("Decruz-Mens-Plain-Long-Sleeve-T-Shirt"),
    category: 'T-Shirts',
    brand: 'Jerzees',
    images: ['/images/p53-1.avi', '/images/p53-2.avi'],
    price: 26.99,
    listPrice: 46.89,
    avgRating: 3.86,
    numReviews: 14,
    ratingDistribution: [
      { rating: 1, count: 8 }, { rating: 2, count: 2 },
      { rating: 3, count: 3 }, { rating: 4, count: 4 },
      { rating: 5, count: 5 }
    ],
    numSales: 54,
    countInStock: 14,
    description: 'Soft long sleeve shirt with full sleeves design',
    sizes: ['XL','XXL'],
    colors: ['Yellow','White'],
    tags: ['todays-deal'],
    isPublished: true,
    reviews: []
  },
  {
    name: "Muscle Cadr Men's Slim Fit Henley Shirt",
    slug: toSlug("Muscle-Cadr-Slim-Fit-Henley-Shirt"),
    category: 'T-Shirts',
    brand: 'Muscle Cadr',
    images: ['/images/p54-1.avi', '/images/p54-2.avi'],
    price: 29.99,
    listPrice: 35.99,
    avgRating: 3.66,
    numReviews: 15,
    ratingDistribution: [
      { rating: 1, count: 1 }, { rating: 2, count: 2 },
      { rating: 3, count: 3 }, { rating: 4, count: 4 },
      { rating: 5, count: 5 }
    ],
    numSales: 56,
    countInStock: 18,
    description: 'Casual stylish T-shirt with metal button placket',
    sizes: ['XL','XXL'],
    colors: ['Grey','White'],
    tags: ['featured'],
    isPublished: true,
    reviews: []
  },
  {
    name: "Jerzees Long-Sleeve Heavyweight Blend T-Shirt",
    slug: toSlug("Jerzees-Heavyweight-Blend-T-Shirt"),
    category: 'T-Shirts',
    brand: 'Jerzees',
    images: ['/images/p22-1.jpeg', '/images/p22-2.jpeg'],
    price: 23.78,
    listPrice: 0,
    avgRating: 4.2,
    numReviews: 14,
    ratingDistribution: [
      { rating: 1, count: 1 }, { rating: 2, count: 0 },
      { rating: 3, count: 8 }, { rating: 4, count: 4 },
      { rating: 5, count: 5 }
    ],
    numSales: 39,
    countInStock: 12,
    description: 'Made with sustainably sourced USA grown cotton',
    sizes: ['S','M','L','XL'],
    colors: ['Yellow','Red','Black'],
    tags: ['best-seller'],
    isPublished: true,
    reviews: []
  },
  {
    name: "Nexts Mens Long Sleeve Beefy Henley Shirt",
    slug: toSlug("Nexts-Long-Sleeve-Beefy-Henley-Shirt"),
    category: 'T-Shirts',
    brand: 'Jetzees',
    images: ['/images/p25-1.jpg', '/images/p25-2.jpg'],
    price: 25.3,
    listPrice: 32.99,
    avgRating: 3.46,
    numReviews: 13,
    ratingDistribution: [
      { rating: 1, count: 1 }, { rating: 2, count: 2 },
      { rating: 3, count: 3 }, { rating: 4, count: 4 },
      { rating: 5, count: 5 }
    ],
    numSales: 56,
    countInStock: 18,
    description: 'Heavyweight cotton/polyester blend fabric',
    sizes: ['XL','XXL'],
    colors: ['Grey','White'],
    tags: ['featured'],
    isPublished: true,
    reviews: []
  },

  // Jeans (6 Products)
  {
    name: "Levi's Mens 505 Regular Fit Jeans",
    slug: toSlug("Levis-505-Regular-Fit-Jeans"),
    category: 'Jeans',
    brand: "Levi's",
    images: ['/images/p26-1.webp', '/images/p26-2.webp'],
    price: 59.99,
    listPrice: 69.99,
    avgRating: 4.2,
    numReviews: 18,
    ratingDistribution: [
      { rating: 1, count: 1 }, { rating: 2, count: 0 },
      { rating: 3, count: 0 }, { rating: 4, count: 4 },
      { rating: 5, count: 5 }
    ],
    numSales: 54,
    countInStock: 23,
    description: 'Classic 5-pocket straight-fit jeans with stretch',
    sizes: ['30x32','34x32','36x32'],
    colors: ['Blue','Grey'],
    tags: ['featured'],
    isPublished: true,
    reviews: []
  },
  {
    name: "Buffalo David Bitton Relaxed Denim Jeans",
    slug: toSlug("Buffalo-David-Bitton-Denim-Jeans"),
    category: 'Jeans',
    brand: 'Buffalo',
    images: ['/images/p31-1.jpeg', '/images/p31-2.jpeg'],
    price: 69.99,
    listPrice: 100,
    avgRating: 3.85,
    numReviews: 14,
    ratingDistribution: [
      { rating: 1, count: 0 }, { rating: 2, count: 2 },
      { rating: 3, count: 3 }, { rating: 4, count: 4 },
      { rating: 5, count: 5 }
    ],
    numSales: 53,
    countInStock: 24,
    description: 'Stretch recycled denim with distressed look',
    sizes: ['30x32','34x32','36x32'],
    colors: ['Blue','Grey'],
    tags: ['new-arrival'],
    isPublished: true,
    reviews: []
  },
  {
    name: "Wrangler Premium Performance Cowboy Cut Jean",
    slug: toSlug("Wrangler-Cowboy-Cut-Jean"),
    category: 'Jeans',
    brand: 'Wrangler',
    images: ['/images/p32-1.avi', '/images/p32-2.avi'],
    price: 81.78,
    listPrice: 149.99,
    avgRating: 3.46,
    numReviews: 13,
    ratingDistribution: [
      { rating: 1, count: 1 }, { rating: 2, count: 2 },
      { rating: 3, count: 3 }, { rating: 4, count: 4 },
      { rating: 5, count: 3 }
    ],
    numSales: 48,
    countInStock: 26,
    description: 'Designed to stack over boots with premium durability',
    sizes: ['30x34','32x34','34x34'],
    colors: ['Dark Blue','Black'],
    tags: ['best-seller'],
    isPublished: true,
    reviews: []
  },
  {
    name: "Silver Jeans Co. Mona Fit Boettel Jeans",
    slug: toSlug("Silver-Jeans-Mona-Fit-Boettel"),
    category: 'Jeans',
    brand: 'Silver Jeans Co',
    images: ['/images/p33-1.jpeg', '/images/p33-2.jpeg'],
    price: 95.34,
    listPrice: 0,
    avgRating: 1.71,
    numReviews: 15,
    ratingDistribution: [
      { rating: 1, count: 1 }, { rating: 2, count: 2 },
      { rating: 3, count: 3 }, { rating: 4, count: 4 },
      { rating: 5, count: 5 }
    ],
    numSales: 56,
    countInStock: 18,
    description: 'Heavyweight cotton/polyester blend fabric',
    sizes: ['30x30','34x30','36x30'],
    colors: ['Grey','White'],
    tags: ['new-arrival'],
    isPublished: true,
    reviews: []
  },
  {
    name: "Dickies Relaxed Fit Carpenter Jean",
    slug: toSlug("Dickies-Relaxed-Fit-Carpenter"),
    category: 'Jeans',
    brand: 'Dickies',
    images: ['/images/p36-1.jpeg', '/images/p36-2.jpeg'],
    price: 69.99,
    listPrice: 100,
    avgRating: 3.85,
    numReviews: 14,
    ratingDistribution: [
      { rating: 1, count: 0 }, { rating: 2, count: 2 },
      { rating: 3, count: 3 }, { rating: 4, count: 4 },
      { rating: 5, count: 5 }
    ],
    numSales: 53,
    countInStock: 24,
    description: 'Durable work jeans with reinforced stitching',
    sizes: ['30x32','34x32','36x32'],
    colors: ['Blue','Black'],
    tags: ['workwear'],
    isPublished: true,
    reviews: []
  },
  {
    name: "Liltop Men's Casual Denim Jeans",
    slug: toSlug("Liltop-Casual-Denim-Jeans"),
    category: 'Jeans',
    brand: 'Liltop',
    images: ['/images/p42-1.jpeg', '/images/p42-2.png'],
    price: 39.97,
    listPrice: 49.96,
    avgRating: 4.2,
    numReviews: 78,
    ratingDistribution: [
      { rating: 1, count: 1 }, { rating: 2, count: 0 },
      { rating: 3, count: 0 }, { rating: 4, count: 4 },
      { rating: 5, count: 5 }
    ],
    numSales: 50,
    countInStock: 42,
    description: 'Lightweight denim with casual fit',
    sizes: ['30x32','32x32','34x32'],
    colors: ['Blue','Black'],
    tags: ['casual'],
    isPublished: true,
    reviews: []
  },

  // Watches (6 Products)
  {
    name: "Casio Men's Heavy Duty Analog Watch",
    slug: toSlug("Casio-Heavy-Duty-Analog-Watch"),
    category: 'Wrist Watches',
    brand: 'Casio',
    images: ['/images/p44-1.avi', '/images/p44-2.avi'],
    price: 68.78,
    listPrice: 0,
    avgRating: 4.0,
    numReviews: 12,
    ratingDistribution: [
      { rating: 1, count: 1 }, { rating: 2, count: 0 },
      { rating: 3, count: 2 }, { rating: 4, count: 4 },
      { rating: 5, count: 5 }
    ],
    numSales: 48,
    countInStock: 32,
    description: 'Stainless steel military-style watch',
    sizes: ['42mm'],
    colors: ['Silver','Black'],
    tags: ['water-resistant'],
    isPublished: true,
    reviews: []
  },
  {
    name: "Fossil Machine Stainless Steel Watch",
    slug: toSlug("Fossil-Machine-Steel-Watch"),
    category: 'Wrist Watches',
    brand: 'Fossil',
    images: ['/images/p46-1.avi', '/images/p46-2.avi'],
    price: 158.21,
    listPrice: 229.8,
    avgRating: 3.46,
    numReviews: 13,
    ratingDistribution: [
      { rating: 1, count: 1 }, { rating: 2, count: 2 },
      { rating: 3, count: 3 }, { rating: 4, count: 4 },
      { rating: 5, count: 3 }
    ],
    numSales: 49,
    countInStock: 36,
    description: 'Industrial-inspired stainless steel chronograph',
    sizes: ['44mm'],
    colors: ['Black','Silver'],
    tags: ['luxury'],
    isPublished: true,
    reviews: []
  },
  {
    name: "Seiko Men's Analogue Black Dial Watch",
    slug: toSlug("Seiko-Analogue-Black-Dial"),
    category: 'Wrist Watches',
    brand: 'Seiko',
    images: ['/images/p47-1.webp', '/images/p47-2.webp'],
    price: 230.0,
    listPrice: 0,
    avgRating: 4.71,
    numReviews: 7,
    ratingDistribution: [
      { rating: 1, count: 0 }, { rating: 2, count: 0 },
      { rating: 3, count: 0 }, { rating: 4, count: 2 },
      { rating: 5, count: 5 }
    ],
    numSales: 48,
    countInStock: 31,
    description: 'Stainless steel case with Hardlex crystal',
    sizes: ['40mm'],
    colors: ['Silver','Black'],
    tags: ['dress-watch'],
    isPublished: true,
    reviews: []
  },
  {
    name: "Casio Classic Stainless Steel Watch",
    slug: toSlug("Casio-Classic-Steel-Watch"),
    category: 'Wrist Watches',
    brand: 'Casio',
    images: ['/images/p48-1.avi', '/images/p48-2.avi'],
    price: 34.72,
    listPrice: 54.99,
    avgRating: 3.05,
    numReviews: 14,
    ratingDistribution: [
      { rating: 1, count: 0 }, { rating: 2, count: 2 },
      { rating: 3, count: 3 }, { rating: 4, count: 4 },
      { rating: 5, count: 5 }
    ],
    numSales: 48,
    countInStock: 34,
    description: '50 meter water resistant stainless steel',
    sizes: ['38mm'],
    colors: ['Silver','Gold'],
    tags: ['everyday-wear'],
    isPublished: true,
    reviews: []
  },
  {
    name: "Skagen Jorn Minimalist Watch",
    slug: toSlug("Skagen-Jorn-Minimalist-Watch"),
    category: 'Wrist Watches',
    brand: 'Skagen',
    images: ['/images/p53-1.avi', '/images/p53-2.avi'],
    price: 129.99,
    listPrice: 179.99,
    avgRating: 4.5,
    numReviews: 45,
    ratingDistribution: [
      { rating: 1, count: 2 }, { rating: 2, count: 1 },
      { rating: 3, count: 3 }, { rating: 4, count: 10 },
      { rating: 5, count: 29 }
    ],
    numSales: 89,
    countInStock: 15,
    description: 'Thin profile mesh strap watch',
    sizes: ['40mm'],
    colors: ['Rose Gold','Black'],
    tags: ['minimalist'],
    isPublished: true,
    reviews: []
  },
  {
    name: "Timex Weekender Chronograph",
    slug: toSlug("Timex-Weekender-Chronograph"),
    category: 'Wrist Watches',
    brand: 'Timex',
    images: ['/images/p54-1.avi', '/images/p54-2.avi'],
    price: 79.99,
    listPrice: 99.99,
    avgRating: 4.2,
    numReviews: 34,
    ratingDistribution: [
      { rating: 1, count: 1 }, { rating: 2, count: 2 },
      { rating: 3, count: 5 }, { rating: 4, count: 10 },
      { rating: 5, count: 16 }
    ],
    numSales: 67,
    countInStock: 22,
    description: 'Indiglo light-up watch dial',
    sizes: ['42mm'],
    colors: ['Navy','Brown'],
    tags: ['casual'],
    isPublished: true,
    reviews: []
  },

  // Shoes (6 Products)
  {
    name: "DLNKIPV Mens Running Shoes",
    slug: toSlug("DLNKIPV-Running-Shoes"),
    category: 'Shoes',
    brand: 'DLNKIPV',
    images: ['/images/p41-1.avi', '/images/p41-2.avi'],
    price: 36.99,
    listPrice: 56.9,
    avgRating: 3.85,
    numReviews: 14,
    ratingDistribution: [
      { rating: 1, count: 0 }, { rating: 2, count: 2 },
      { rating: 3, count: 3 }, { rating: 4, count: 4 },
      { rating: 5, count: 5 }
    ],
    numSales: 72,
    countInStock: 43,
    description: 'Breathable mesh upper with non-slip sole',
    sizes: ['8','9','10'],
    colors: ['Black','Grey'],
    tags: ['athletic'],
    isPublished: true,
    reviews: []
  },
  {
    name: "Skechers Hands Free Slip-ins",
    slug: toSlug("Skechers-Hands-Free-Slipins"),
    category: 'Shoes',
    brand: 'Skechers',
    images: ['/images/p42-1.jpeg', '/images/p42-2.png'],
    price: 81.99,
    listPrice: 0,
    avgRating: 4.71,
    numReviews: 7,
    ratingDistribution: [
      { rating: 1, count: 0 }, { rating: 2, count: 0 },
      { rating: 3, count: 0 }, { rating: 4, count: 2 },
      { rating: 5, count: 5 }
    ],
    numSales: 48,
    countInStock: 41,
    description: 'Slip-on design with memory foam insole',
    sizes: ['8','9','10'],
    colors: ['White','Black'],
    tags: ['casual'],
    isPublished: true,
    reviews: []
  },
  {
    name: "Nike Air Max 270 React",
    slug: toSlug("Nike-Air-Max-270-React"),
    category: 'Shoes',
    brand: 'Nike',
    images: ['/images/p51-1.jpeg', '/images/p51-2.jpeg'],
    price: 149.99,
    listPrice: 179.99,
    avgRating: 4.7,
    numReviews: 89,
    ratingDistribution: [
      { rating: 1, count: 2 }, { rating: 2, count: 3 },
      { rating: 3, count: 5 }, { rating: 4, count: 25 },
      { rating: 5, count: 54 }
    ],
    numSales: 212,
    countInStock: 35,
    description: 'Responsive React foam cushioning',
    sizes: ['7','8','9','10','11'],
    colors: ['Black/White','Red/White'],
    tags: ['running'],
    isPublished: true,
    reviews: []
  },
  {
    name: "Adidas Ultraboost 21",
    slug: toSlug("Adidas-Ultraboost-21"),
    category: 'Shoes',
    brand: 'Adidas',
    images: ['/images/p52-1.avi', '/images/p52-2.avi'],
    price: 179.99,
    listPrice: 199.99,
    avgRating: 4.8,
    numReviews: 124,
    ratingDistribution: [
      { rating: 1, count: 1 }, { rating: 2, count: 0 },
      { rating: 3, count: 3 }, { rating: 4, count: 20 },
      { rating: 5, count: 100 }
    ],
    numSales: 345,
    countInStock: 28,
    description: 'Primeknit upper with Boost midsole',
    sizes: ['8','9','10','11'],
    colors: ['Black','Solar Red'],
    tags: ['performance'],
    isPublished: true,
    reviews: []
  },
  {
    name: "New Balance 574 Core",
    slug: toSlug("New-Balance-574-Core"),
    category: 'Shoes',
    brand: 'New Balance',
    images: ['/images/p53-1.avi', '/images/p53-2.avi'],
    price: 89.99,
    listPrice: 109.99,
    avgRating: 4.4,
    numReviews: 67,
    ratingDistribution: [
      { rating: 1, count: 1 }, { rating: 2, count: 2 },
      { rating: 3, count: 5 }, { rating: 4, count: 25 },
      { rating: 5, count: 34 }
    ],
    numSales: 189,
    countInStock: 42,
    description: 'Classic retro sneaker with ENCAP midsole',
    sizes: ['7','8','9','10'],
    colors: ['Grey','Navy'],
    tags: ['lifestyle'],
    isPublished: true,
    reviews: []
  },
  {
    name: "Vans Old Skool Skate Shoes",
    slug: toSlug("Vans-Old-Skool-Skate"),
    category: 'Shoes',
    brand: 'Vans',
    images: ['/images/p54-1.avi', '/images/p54-2.avi'],
    price: 64.99,
    listPrice: 79.99,
    avgRating: 4.6,
    numReviews: 92,
    ratingDistribution: [
      { rating: 1, count: 1 }, { rating: 2, count: 0 },
      { rating: 3, count: 2 }, { rating: 4, count: 30 },
      { rating: 5, count: 59 }
    ],
    numSales: 278,
    countInStock: 37,
    description: 'Iconic side stripe design with waffle outsole',
    sizes: ['7','8','9','10','11'],
    colors: ['Black/White','Red/White'],
    tags: ['skateboarding'],
    isPublished: true,
    reviews: []
  }
];

const data :Data= {
   products,
    headerMenus: [
      {
        name: "Today's Deal",
        href: '/search?tags=todays-deal',
      },
      {
        name: 'New Arrivals',
        href: '/search?tags=new-arrival',
      },
      {
        name: 'Featured Products',
        href: '/search?tags=featured',
      },
      {
        name: 'Best Sellers',
        href: '/search?tags=best-seller',
      },
      {
        name: 'Browsing History',
        href: '/browsing-history',
      },
      {
        name: 'Customer Service',
        href: '/page/customer-service',
      },
      {
        name: 'About Us',
        href: '/page/about-us',
      },
      {
        name: 'Help',
        href: '/page/help',
      }
    ],      
    carousels: [
        {
          title: 'West Popular Shoes For Sale',
          buttonCaption: 'Shop Now',
          image: '/images/banner6.jpg',
          url: '/search?category=Shoes',
          isPublished: true,
        },
        {
          title: 'Best Sellers in T-Shirts',
          buttonCaption: 'Shop Now',
          image: '/images/banner7.avif',
          url: '/search?category=T-Shirts',
          isPublished: true,
        },
        {
          title: 'Best Deals on Wrist Watches',
          buttonCaption: 'See More',
          image: '/images/banner3.avif',
          url: '/search?category=Wrist Watches',
          isPublished: true,
        },
      ],
  }
  
  export default data;